# Generated by Django 2.2 on 2019-04-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_menu_page_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_body',
        ),
    ]
