# Generated by Django 2.2 on 2019-04-26 00:55

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190425_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_body',
            field=markdownx.models.MarkdownxField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='post_body',
            field=markdownx.models.MarkdownxField(default=''),
        ),
    ]
