# Generated by Django 2.2 on 2019-04-26 04:53

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190426_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_body',
            field=martor.models.MartorField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=martor.models.MartorField(default=''),
        ),
    ]
