# Generated by Django 2.2 on 2019-04-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190426_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_status',
            field=models.CharField(choices=[('1', 'Published'), ('0', 'UnPublished')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_status',
            field=models.CharField(choices=[('1', 'Visible'), ('0', 'Hidden')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='page',
            name='page_status',
            field=models.CharField(choices=[('1', 'Published'), ('0', 'UnPublished')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('1', 'Published'), ('0', 'UnPublished')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='section',
            name='section_status',
            field=models.CharField(choices=[('1', 'Visible'), ('0', 'Hidden')], default='1', max_length=1),
        ),
    ]
