# Generated by Django 2.2 on 2019-04-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190426_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_featured',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='post_headline',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='1', max_length=1),
        ),
    ]
