# Generated by Django 2.2 on 2019-05-07 03:08

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190507_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='post_header',
        ),
        migrations.AddField(
            model_name='page',
            name='page_header',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='', height_field='page_header_image_height', upload_to='page', verbose_name='Header', width_field='page_header_image_width'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_header_image_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_header_image_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_featured_image_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_featured_image_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_header_image_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_header_image_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_featured_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='', height_field='post_featured_image_height', upload_to='post', verbose_name='Featured', width_field='post_featured_image_width'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_header',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='', height_field='post_header_image_height', upload_to='post', verbose_name='Header', width_field='post_header_image_width'),
        ),
    ]
