# Generated by Django 2.2 on 2019-05-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190507_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.ManyToManyField(related_name='categories', to='blog.Category'),
        ),
    ]
